### ISSUE TITLE
New Addition : Streamlit Badge

### ISSUE THREAD

**Issue by AM1CODES** [alexandresanlim/Badges4-README.md-Profile#116]
Streamlit is something  that people use a lot to deploy their machine learning models and it would be really handy to have a streamlit badge. I was wondering if i could contribute that.

**Comment by alexandresanlim** [comment]
Hello @AM1CODES , you can see [this session](https://github.com/alexandresanlim/Badges4-README.md-Profile#-contribute-) to do it.

**Comment by alexandresanlim** [comment]
Resolves here #118
