### ISSUE TITLE
Add Jasmine, Mocha Badges

### ISSUE THREAD

**Issue by codebriefcase** [alexandresanlim/Badges4-README.md-Profile#152]
Add badges for Jasmine and Mocka in the sections of the framework.

Relevant URLs are as follows -
- https://jasmine.github.io/
- https://mochajs.org/

// Please add a contribution document describing how to contribute to this repo. (if possible)

**Comment by helloankit** [comment]
Thanks!

May I ask if there is any way through which I can add more badges directly through PR ?

**Comment by david-slatinek** [comment]
Sure, add new badges and make a new PR. When that PR is closed, your added badges will be available.
