### ISSUE TITLE
How can I just show the icon with no text?

### ISSUE THREAD

**Issue by joisaac** [alexandresanlim/Badges4-README.md-Profile#17]
Congratulations for the repository, it's really helpful, what if I just want a badge to show the icon without any text whatsoever, how can I perform this?

**Comment by pablomatiasgomez** [comment]
You can remove/change the text that is after `/badge/`

For example:

<img src="https://img.shields.io/badge/-25D366?style=for-the-badge&logo=whatsapp&logoColor=white"/>
