### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by Sergih28** [alexandresanlim/Badges4-README.md-Profile#173]
Would be good if the project added a **LICENSE**, like _MIT_ for example.

**Comment by alexandresanlim** [comment]
I don't understand this project as a software, so I wouldn't know if a license is viable

**Comment by Sergih28** [comment]
🤔 Mmm.. Idk. But if the purpose of the project is for everyone to contribute, I guess it'd be better to have a license.
But I'm quite new around here, so idk.
