### ISSUE TITLE
Add openWRT?

### ISSUE THREAD

**Issue by deep5050** [alexandresanlim/Badges4-README.md-Profile#175]
It would be great to have the openWrt badge.
https://openwrt.org/docs/guide-graphic-designer/openwrt-logo

Thanks

**Comment by alexandresanlim** [comment]
Its [here](https://github.com/alexandresanlim/Badges4-README.md-Profile#-os-) at the end of the list

**Comment by deep5050** [comment]
oops, missed it.. thanks man
