### ISSUE TITLE
wrong logo for Perl

### ISSUE THREAD

**Issue by deep5050** [alexandresanlim/Badges4-README.md-Profile#18]
i guess logo for the Perl language is wrong! why is it an onion?

**Comment by alexandresanlim** [comment]
Hello, i found this explanation on wikipedia:

"Onion symbol, The onion logo used by The Perl Foundation
The Perl Foundation owns an alternative symbol, an onion, which it licenses to its subsidiaries, Perl Mongers, PerlMonks, Perl.org, and others.[69] The symbol is a visual pun on pearl onion."
