### ISSUE TITLE
Handlebars logo

### ISSUE THREAD

**Issue by GrinninBarrett** [alexandresanlim/Badges4-README.md-Profile#211]
The logo for Handlebars.js is not appearing in the badge, though Simple Icons does have an icon for it. Here is the URL I created:

https://img.shields.io/badge/Handlebars.js-f0772b?style=for-the-badge&logo=handlebarsdotjs&logoColor=black

I chose "handlebarsdotjs" because it is the name of the icon in the [Simple Icons repo](https://github.com/simple-icons/simple-icons/blob/develop/icons/handlebarsdotjs.svg), but I also tried to replace it with "handlebars" and "handlebars.js", and none of them are rendering the logo.

**Comment by david-slatinek** [comment]
Resolves #217
