### ISSUE TITLE
Please add huggingFace, Render, Weights&Biases

### ISSUE THREAD

**Issue by nakshatrasinghh** [alexandresanlim/Badges4-README.md-Profile#214]

**Comment by gurjeetsinghvirdee** [comment]
These badges doesn't exist right now! You can create a issue in [Simple Icons](https://github.com/simple-icons/simple-icons) to make a badge

**Comment by mrhrifat** [comment]
Some logo doesn't exist but one badge is [here](https://img.shields.io/badge/Weights_&_Biases-FFBE00?style=for-the-badge&logo=WeightsAndBiases&logoColor=white).
