### ISSUE TITLE
Add git-badges

### ISSUE THREAD

**Issue by puf17640** [alexandresanlim/Badges4-README.md-Profile#228]
Hey there! I built a service that makes a few more badges available which are really nice to have on GitHub. Would you include them into your list please? 😁 https://badges.pufler.dev

**Comment by mrhrifat** [comment]
It's nice. And sorry for the interruption. Actually I need a help, How can I get only the number from them without badge title? 
`https://badges.pufler.dev/years/puf17640`
>![Years Badge](https://badges.pufler.dev/years/puf17640)

I just need 5. Is it possible ?

**Comment by Amir-Pourhadi** [comment]
Hello @puf17640 
I included your badges on my github profile page. They are wonderful! 😍
But unfortunately, they are not updated. When I open a badge url on my browser everything is good, but in README file they are not updating 😞

**Comment by puf17640** [comment]
> Hello @puf17640 
> 
> I included your badges on my github profile page. They are wonderful! 😍
> 
> But unfortunately, they are not updated. When I open a badge url on my browser everything is good, but in README file they are not updating 😞 

this is due to github caching a lot of this image stuff from your readme, i cannot change that unfortunately
