### ISSUE TITLE
Mongoose

### ISSUE THREAD

**Issue by Sagar-Sharma-7** [alexandresanlim/Badges4-README.md-Profile#25]
Please add Mongoose logo

Thank you

**Comment by mfdeveloper** [comment]
Hello @Sagar-Sharma-7 !!

See what I described on issue #27

**Comment by RazorShard** [comment]
@Sagar-Sharma-7 As of now theres no logo for the the mongoose npm package. (I took https://www.npmjs.com/package/mongoose as a reference and couldnt find it) Maybe i am wrong. You can make a PR doe read the last part of The readme to know who.
