### ISSUE TITLE
ETL Tools

### ISSUE THREAD

**Issue by AfonsoFeliciano** [alexandresanlim/Badges4-README.md-Profile#268]
Please add ETL and Cloud Tools

- Pentaho Data Integration
- Integration Services
- Talend
- Azure Data Factory
- Azure Synapse
- Databricks
- Spark

**Comment by mrhrifat** [comment]
Some icons do not exist. So I added what I found.
- [Badges](https://github.com/alexandresanlim/Badges4-README.md-Profile/#-etl-)
