### ISSUE TITLE
Requirement of Badge

### ISSUE THREAD

**Issue by Venkatesh-tech** [alexandresanlim/Badges4-README.md-Profile#27]
Please add a KFC badge Related to food...

Thank you...

**Comment by mfdeveloper** [comment]
Hello @Venkatesh-tech !

You can create new badges, and submit a PR for this repo to add a new badge to the `README.md`. See this tutorial below:

[How To Make Custom Language Badges for your Profile using shields.io
](https://javascript.plainenglish.io/how-to-make-custom-language-badges-for-your-profile-using-shields-io-d2aeaf016b6b)

**Comment by Venkatesh-tech** [comment]
Thanks a ton.
