### ISSUE TITLE
Offer for added page under repo.

### ISSUE THREAD

**Issue by SparkScratch-P** [alexandresanlim/Badges4-README.md-Profile#280]
I have added scratch recently to my forked project and have created a pull request. Now, I am here with another innovative offer. Every user, in cluding me, will not search for a given badge..and will obv like to see the collection, and may wany many things that are in SImple Icons, but not here. I will create a dynamic HTML app to fetch all logos.. with features like...` copy URL` , `copy HTML`, ` copy md`, etc. If it is helpful, pls say, i will create.

**Comment by alexandresanlim** [comment]
Of course, I was thinking about it for the future, but if you want to get started, it will definitely be a cool milestone.

**Comment by mrhrifat** [comment]
I'm closing this issue cause of no response although it has been passed too many days but didn't get any response. Dear @SparkScratch-P  if you need to reopen this issue please feel free to do when you've any update about your proposal. Thanks.
