### ISSUE TITLE
Google Sheets Badge

### ISSUE THREAD

**Issue by Sam-Varghese** [alexandresanlim/Badges4-README.md-Profile#29]
Hi sir, I just want to request you to please make a badge for google sheets as well.

**Comment by alexandresanlim** [comment]
Hi, it`s here:
https://github.com/alexandresanlim/Badges4-README.md-Profile/blob/master/README.md#-skills-

**Comment by Sam-Varghese** [comment]
Thankyou sir for resolving this issue.
