### ISSUE TITLE
[Feature]: Add .editorconfig badge

### ISSUE THREAD

**Issue by kumartul** [alexandresanlim/Badges4-README.md-Profile#302]

**Comment by mrhrifat** [comment]
I can't get the category type of `Editor Config`. Please make clear it, to add this.

**Comment by mrhrifat** [comment]
I can't get the category type of `Editor Config`. Please make clear it, so that I can add this  properly.

**Comment by gurjeetsinghvirdee** [comment]
> I can't get the category type of `Editor Config`. Please make clear it, so that I can add this properly.


#303 
That was a editor plugin I added

**Comment by kumartul** [comment]
This is the official page of .editorconfig: [EditorConfig](https://editorconfig.org/)
You can find the logo there

**Comment by mrhrifat** [comment]
Take your [Badge](https://github.com/alexandresanlim/Badges4-README.md-Profile#-ide-plugin-)

**Comment by mrhrifat** [comment]
Take your [Badge](https://github.com/alexandresanlim/Badges4-README.md-Profile#-ide-plugin-)

**Comment by kumartul** [comment]
Glad to have that :)
