### ISSUE TITLE
Create custom icons guide

### ISSUE THREAD

**Issue by mfdeveloper** [alexandresanlim/Badges4-README.md-Profile#33]
Hello @alexandresanlim !!

First of all, thank you so much for these awesome badges 🤩 

So, can you share in this repo some **guide** in `.md` or **wiki** pages with the steps to create and submit new icons? I know that I should use the [shields.io](https://shields.io) and the [simpleicons.org](https://simpleicons.org) but I'm not sure how can I get the same aesthetics like these badges here (e.g. the height and the flat styles).

Also, a section in this guide with the requirements to how can I submit a pull request and add the new icon in the correct tables in [README.md](https://github.com/alexandresanlim/Badges4-README.md-Profile/blob/master/README.md) will be great!

Maybe these clear steps guide, could reduce the requests for "new icons" here 😄

Thank you so much for your attention!!

**Comment by StokicDusan** [comment]
If it's about the aesthetics, [Shields.io](https://shields.io) has an option for the style displayed in this README
![bagde-style](https://user-images.githubusercontent.com/69325657/115715059-12b22580-a378-11eb-819f-fcfd59879b3a.png)

You can edit the style in the URL to see how they change
https://img.shields.io/badge/GitHub-100000?**style=for-the-badge**&logo=github&logoColor=white

**Comment by mfdeveloper** [comment]
@StokicDusan Thanks for your response!

This image helps a lot, but I was looking for a more "step-by-step" guide. After that, I found the tutorial below that together with your tip here, I could create new badges sucessfully 😄 

**Tutorial:** [How To Make Custom Language Badges for your Profile using shields.io
](https://javascript.plainenglish.io/how-to-make-custom-language-badges-for-your-profile-using-shields-io-d2aeaf016b6b)

I've created the PR #34 adding more two badges to the table list on the **README**!!
