### ISSUE TITLE
Duplicate Badges

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [alexandresanlim/Badges4-README.md-Profile#357]
Hii @mrhrifat @alexandresanlim 
Can I remove duplicate badges!! Like some of the badges are repeated in different slots `Codechef` `Dribble` `Behance` etc.
It's better to remove the same badge from a different section!!

**Comment by mrhrifat** [comment]
Hello... Yes you can remove them. But don't remove any badges from his the closest related section.
Like I just saw that `Codechef` are available in `Social & IDE` section but it a learning platform.
So make your changes, I will review it. 
Beside you can check my new Open Source named [Web Badge](https://github.com/mrhrifat/web-badge). If you wish you can contribute here. I need many improvement on this.

**Comment by gurjeetsinghvirdee** [comment]
> Hello... Yes you can remove them. But don't remove any badges from his the closest related section. Like I just saw that `Codechef` are available in `Social & IDE` section but it a learning platform. So make your changes, I will review it. Beside you can check my new Open Source named [Web Badge](https://github.com/mrhrifat/web-badge). If you wish you can contribute here. I need many improvement on this.

Ok I will make a note first which badges belong with which platforms then will make a PR
Your project was better than simple icons, every time I use simple icons I think my PC lagged but that was a site issue

**Comment by mrhrifat** [comment]
Thanks but my site also very slow. I'm trying to fix the problem.

**Comment by gurjeetsinghvirdee** [comment]
> Thanks but my site also very slow. I'm trying to fix the problem.

I think the first issue was site was slow & the second when we hover over the background color changed to white so that was another issue anyway 
if I have to add an icon so where do I put it in `slug.json`  ?

**Comment by gurjeetsinghvirdee** [comment]
Share your mail or something it's better to talk there not here ;)

**Comment by mrhrifat** [comment]
I know there are many bugs & I do notice them while I'm develop this site. Thanks for notice them. Recently I add React Router. You can contact me with [LinkedIn or Gmail](https://github.com/mrhrifat#reach-me)
