### ISSUE TITLE
Add badge for Remix JS

### ISSUE THREAD

**Issue by canaryGrapher** [alexandresanlim/Badges4-README.md-Profile#389]
Framework from Full Stack Web Development [Link](https://remix.run/)

**Comment by mrhrifat** [comment]
It's not available as a logo now, whenever it will, ৷ We or someone will make it. You can create an issue for make this logo [here](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml)
