### ISSUE TITLE
Add HarmonyOS

### ISSUE THREAD

**Issue by yusancky** [alexandresanlim/Badges4-README.md-Profile#439]
Please add [**HarmonyOS**](https://www.harmonyos.com/).

**Comment by mrhrifat** [comment]
It's not available as a logo now, whenever it will, I or someone else will make it. You can create an issue for make this logo [here](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml)

**Comment by yusancky** [comment]
> It's not available as a logo now, whenever it will, I or someone else will make it. You can create an issue for make this logo [here](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml)

Thanks very much. :heart: 
In addition, I create the issue https://github.com/simple-icons/simple-icons/issues/7625 for it 4 hours ago. :smile:

**Comment by mrhrifat** [comment]
I merge it. Thanks for your contribution.
