### ISSUE TITLE
Asking for a new logo

### ISSUE THREAD

**Issue by Mouly22** [alexandresanlim/Badges4-README.md-Profile#444]
Can you add a badge for 'Kaggle' ?

**Comment by Walidoux** [comment]
Can you also add a badge for solidjs ? (alternative to reactjs)
link: https://www.solidjs.com/

**Comment by mrhrifat** [comment]
> Can you add a badge for 'Kaggle' ?

Assalamu Alaikum, @Mouly22 ! Your requested badge `Kaggle` has been added. Get it from [here](https://github.com/alexandresanlim/Badges4-README.md-Profile#-community-)

**Comment by mrhrifat** [comment]
> Can you also add a badge for solidjs ? (alternative to reactjs) link: https://www.solidjs.com/

Assalamu Alaikum, @Walidoux  ! Your requested badge `SolidJS` has been added. Get it from [this](https://github.com/alexandresanlim/Badges4-README.md-Profile#-frameworks--library-) section.

**Comment by Mouly22** [comment]
> > Can you add a badge for 'Kaggle' ?
> 
> Assalamu Alaikum, @Mouly22 ! Your requested badge `Kaggle` has been added. Get it from [here](https://github.com/alexandresanlim/Badges4-README.md-Profile#-community-)

Walaikum Assalam, Thank you @mrhrifat
