### ISSUE TITLE
Question regarding the width of Readme.md

### ISSUE THREAD

**Issue by Anmol-Baranwal** [alexandresanlim/Badges4-README.md-Profile#476]
I just wanted to ask how you have **increased the width** of GitHub readme while generally, it is fixed and long code breaks into another line.

- Have you used [Widescreen for GitHub](https://chrome.google.com/webstore/detail/widescreen-for-github/elikdceclccjilahimjfceoalhdbndan?hl=en)?

- Are there any options via workflow or code?

Please add the label: `question` @mrhrifat

**Comment by mrhrifat** [comment]
I didn't `increased the width` of GitHub README nor I've use the extension you've mentioned. I think you notice that different,  because of `GitHub's community` build or update it that way & your device screen size.
