### ISSUE TITLE
Badge request: Java

### ISSUE THREAD

**Issue by SathiraSriSathsara** [alexandresanlim/Badges4-README.md-Profile#622]
Can you add Java Icon as well?
![java](https://axcvkiu68ktx.objectstorage.ap-singapore-1.oci.customer-oci.com/n/axcvkiu68ktx/b/bucket-20231229-2320/o/My%2Fjava.png)

**Comment by alexandresanlim** [comment]
We can't add because [this](https://github.com/simple-icons/simple-icons/issues/7374)

**Comment by SathiraSriSathsara** [comment]
> We can't add because [this](https://github.com/simple-icons/simple-icons/issues/7374)

:(
