### ISSUE TITLE
Kotlin Image not found: Error 404 and Java Image missing as well

### ISSUE THREAD

**Issue by Hassaan68** [alexandresanlim/Badges4-README.md-Profile#660]
Please fix Kotlin image not found error and add Java image as well

**Comment by Akshat-Sabharwal** [comment]
Use https://img.shields.io/badge/Java-0983C1?style=for-the-badge&logo=openjdk&logoColor=E61C20. Replace the color scheme with that of your choice. Also the logo name has been changed to **openjdk** and not java or Java.

**Comment by Akshat-Sabharwal** [comment]
Use **kotlin** for logo
