### ISSUE TITLE
Badge Request: TryHackMe

### ISSUE THREAD

**Issue by sealldeveloper** [alexandresanlim/Badges4-README.md-Profile#667]
Should go under [Security Platforms](https://github.com/alexandresanlim/Badges4-README.md-Profile?tab=readme-ov-file#-security-platforms-)

URL : `https://img.shields.io/badge/TryHackMe-595959?style=for-the-badge&logo=tryhackme&logoColor=white`
Preview:
<img src="https://img.shields.io/badge/TryHackMe-595959?style=for-the-badge&logo=tryhackme&logoColor=white">

Text: `TryHackMe`
Hex Color: `#595959`
Logo Name: `tryhackme`

**Comment by Moewenmann** [comment]
Created a pull request.

![prev](https://img.shields.io/badge/TryHackMe-212C42?style=for-the-badge&logo=TryHackMe&logoColor=white)

**Comment by alexandresanlim** [comment]
Resolves on #679
