### ISSUE TITLE
New Menu Item

### ISSUE THREAD

**Issue by dhyeythumar** [alexandresanlim/Badges4-README.md-Profile#86]
I think a new item can be added to the menu for `Web Hosting Platforms`.
For example: Glitch, Repl.it, Heroku, etc.

**Comment by RazorShard** [comment]
@dhyeythumar This is already done in the form of `Web Cloud Services`. Though I got to admit its not complete, Few hosts are there in the `Frameworks` Sections. Like Netlify, Heroku, etc.

**Comment by dhyeythumar** [comment]
So is it possible to remove Netlify, Heroku, Glitch, Repl.it etc from Frameworks section and add them to the Web Cloud Services section?

**Comment by RazorShard** [comment]
@dhyeythumar You can do it yourself make a Pull Request

**Comment by dhyeythumar** [comment]
Ok I will create a PR for this.
